use_frameworks!

platform :ios, '8.0'

target 'PrivateRepositoryTest_Example' do
  pod 'PrivateRepositoryTest', :path => '../'

  target 'PrivateRepositoryTest_Tests' do
    inherit! :search_paths

    
  end
end
